# Generated by Django 6.1 on 2026-08-23 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('sandbox_consumer_key', models.CharField(blank=True, max_length=255)),
                ('sandbox_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('sandbox_shortcode', models.CharField(blank=True, max_length=20)),
                ('sandbox_passkey', models.CharField(blank=True, max_length=255)),
                ('sandbox_callback_url', models.URLField(blank=True)),
                ('production_consumer_key', models.CharField(blank=True, max_length=255)),
                ('production_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('production_shortcode', models.CharField(blank=True, max_length=20)),
                ('production_passkey', models.CharField(blank=True, max_length=255)),
                ('production_callback_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daraja settings',
                'verbose_name_plural': 'Daraja settings',
                'db_table': 'accounts_daraja_settings',
            },
        ),
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STUDENT_FEES', 'Student fees'), ('POCKET_MONEY', 'Pocket money'), ('OPERATIONS', 'Operations'), ('CAPITAL', 'Capital'), ('OTHER', 'Other')], max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('payment_modes', models.JSONField(default=list)),
                ('academic_level_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_school_account',
                'ordering': ['category', 'name'],
            },
        ),
    ]
