# Generated by Django 6.1 on 2026-08-23 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_school_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, db_index=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('transaction_date', models.CharField(blank=True, max_length=20)),
                ('account_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='RECEIVED', max_length=20)),
                ('raw_payload', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_callbacks', to='billing.payment')),
            ],
            options={
                'db_table': 'accounts_mpesa_callback_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
