# Generated by Django 6.1 on 2026-08-23 04:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_mpesa_callback_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('STK_PUSH', 'STK Push (M-Pesa)'), ('MANUAL_MPESA', 'Manual M-Pesa'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('TRADE', 'Trade')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(max_length=120)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top_ups', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_top_ups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_account_topup',
                'ordering': ['-created_at'],
            },
        ),
    ]
