# Generated by Django 6.1 on 2026-08-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_account_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttopup',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='APPROVED', max_length=20),
        ),
    ]
