# Generated by Django 6.1 on 2026-08-23 04:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_account_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvote',
            name='allocation_mode',
            field=models.CharField(choices=[('AMOUNT', 'Fixed amount'), ('PERCENTAGE', 'Percentage of account balance')], default='AMOUNT', max_length=20),
        ),
        migrations.AddField(
            model_name='accountvote',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used when allocation_mode is PERCENTAGE (0.01–100).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
