# Generated by Django 6.1 on 2026-08-23 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_vote_allocation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountvote',
            options={'ordering': ['allocation_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='accountvote',
            name='allocation_order',
            field=models.PositiveIntegerField(default=1, help_text='Priority order for allocating funds on this account (1 = first).'),
        ),
        migrations.AddConstraint(
            model_name='accountvote',
            constraint=models.UniqueConstraint(fields=('account', 'allocation_order'), name='uniq_account_vote_allocation_order'),
        ),
    ]
