# Generated by Django 6.1 on 2026-08-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_vote_allocation_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolaccount',
            name='vote_fund_allocation',
            field=models.CharField(choices=[('EQUAL', 'Equally among votes'), ('PRIORITY_ORDER', 'By allocation order (priority)')], default='PRIORITY_ORDER', help_text='How incoming funds are allocated across votes on this account.', max_length=32),
        ),
    ]
