# Generated by Django 6.1 on 2026-08-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_school_account_vote_fund_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvote',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20),
        ),
    ]
