# Generated by Django 6.1 on 2026-08-23 04:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_vote_status_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvote',
            name='allocation_mode',
            field=models.CharField(choices=[('AMOUNT', 'Fixed amount'), ('PERCENTAGE', 'Percentage of total topped up')], default='AMOUNT', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountvote',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share of the account’s total approved top-ups (0.01–100).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
