# Generated by Django 6.1 on 2026-08-23 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_vote_percentage_of_topups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Only one financial year should be marked current.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_years_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_financial_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Marks the term Accounts is currently operating in.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='billing.financialyear')),
            ],
            options={
                'db_table': 'accounts_financial_term',
                'ordering': ['start_date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('financial_year', 'name'), name='uniq_financial_year_term_name')],
            },
        ),
    ]
