# Generated by Django 6.1 on 2026-08-23 05:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_financial_year_and_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvote',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Allocated amount. May be 0 until the account is topped up.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='accountvote',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Share of the account’s total approved top-ups (whole number, 1–100).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='financialterm',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Only valid on the current financial year; defaults to today’s term.'),
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('academic_level_ids', models.JSONField(blank=True, default=list, help_text='Curriculum academic level IDs this structure applies to.')),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures_created', to=settings.AUTH_USER_MODEL)),
                ('financial_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='billing.financialterm')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='billing.financialyear')),
            ],
            options={
                'db_table': 'accounts_fee_structure',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.feestructure')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structure_lines', to='billing.accountvote')),
            ],
            options={
                'db_table': 'accounts_fee_structure_line',
                'ordering': ['vote__allocation_order', 'vote__name'],
                'constraints': [models.UniqueConstraint(fields=('structure', 'vote'), name='uniq_fee_structure_vote')],
            },
        ),
    ]
