# Generated by Django 6.1 on 2026-08-23 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_fee_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feecharge',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.feestructure'),
        ),
        migrations.AddField(
            model_name='feecharge',
            name='structure_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.feestructureline'),
        ),
        migrations.AddConstraint(
            model_name='feecharge',
            constraint=models.UniqueConstraint(condition=models.Q(('structure_line__isnull', False)), fields=('student_id', 'structure_line'), name='uniq_student_fee_structure_line'),
        ),
    ]
