# Generated by Django 6.1 on 2026-08-23 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_fee_structure_student_charges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feecharge',
            name='uniq_student_fee_structure_line',
        ),
        migrations.AddIndex(
            model_name='feecharge',
            index=models.Index(fields=['student_id', 'structure_line'], name='accounts_fe_student_752064_idx'),
        ),
    ]
