# Generated by Django 6.1 on 2026-08-24 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


EXPENSE_CATEGORIES = (
    "Stationery",
    "Cleaning materials",
    "Foodstuffs",
    "Laboratory",
    "Sports and games",
    "Uniforms",
    "Maintenance and repairs",
    "Furniture and fittings",
    "Teaching materials",
    "Medical supplies",
    "Fuel and energy",
    "Other",
)

DEPARTMENT_STATIONS = (
    "Administration",
    "Boarding",
    "Kitchen",
    "Science laboratory",
    "Computer laboratory",
    "Library",
    "Sports",
    "Farm",
    "Workshop",
    "Clinic",
    "Store",
    "Accounts",
    "Other",
)


def seed_store_lookups(apps, schema_editor):
    StoreExpenseCategory = apps.get_model("billing", "StoreExpenseCategory")
    StoreDepartmentStation = apps.get_model("billing", "StoreDepartmentStation")
    if not StoreExpenseCategory.objects.exists():
        StoreExpenseCategory.objects.bulk_create(
            [
                StoreExpenseCategory(name=name, sort_order=index)
                for index, name in enumerate(EXPENSE_CATEGORIES, start=1)
            ]
        )
    if not StoreDepartmentStation.objects.exists():
        StoreDepartmentStation.objects.bulk_create(
            [
                StoreDepartmentStation(name=name, sort_order=index)
                for index, name in enumerate(DEPARTMENT_STATIONS, start=1)
            ]
        )


def unseed_store_lookups(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_account_withdraw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDepartmentStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts_store_department_station',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'store expense categories',
                'db_table': 'accounts_store_expense_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('measure', models.CharField(choices=[('PCS', 'Piece'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen'), ('PKT', 'Packet'), ('BOX', 'Box'), ('CTN', 'Carton'), ('REAM', 'Ream'), ('SET', 'Set'), ('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('M', 'Metre'), ('ROLL', 'Roll'), ('TIN', 'Tin'), ('BTL', 'Bottle'), ('BAG', 'Bag')], max_length=12)),
                ('image', models.ImageField(blank=True, upload_to='store/items/%Y/%m/')),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_items_created', to=settings.AUTH_USER_MODEL)),
                ('department_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.storedepartmentstation')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.storeexpensecategory')),
            ],
            options={
                'db_table': 'accounts_store_item',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'department_station', 'measure'), name='uniq_store_item_name_station_measure')],
            },
        ),
        migrations.RunPython(seed_store_lookups, unseed_store_lookups),
    ]
