# Generated by Django 6.1 on 2026-08-24 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_store_stock_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storestockmovement',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('UNPAID', 'Not paid'), ('PENDING', 'Pending payment'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid')], max_length=20),
        ),
        migrations.CreateModel(
            name='StoreSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=24, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_suppliers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_store_supplier',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='storestockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='billing.storesupplier'),
        ),
    ]
