# Generated by Django 5.0.14 on 2026-10-05 04:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_store_supplier_and_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storestockmovement',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='storestockmovement',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_received', to='billing.storedepartmentstation'),
        ),
        migrations.AddField(
            model_name='storestockmovement',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='storestockmovement',
            name='out_reason',
            field=models.CharField(blank=True, choices=[('TRANSFER', 'Transfer to department'), ('WASTE', 'Waste'), ('RETURN', 'Return to supplier')], max_length=20),
        ),
        migrations.CreateModel(
            name='StoreSupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('reference_number', models.CharField(max_length=120)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_supplier_payments_created', to=settings.AUTH_USER_MODEL)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='billing.storestockmovement')),
                ('withdrawal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment', to='billing.accountwithdraw')),
            ],
            options={
                'db_table': 'accounts_store_supplier_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
