# Generated by Django 5.0.14 on 2026-10-05 05:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_storestockmovement_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolaccount',
            name='category',
            field=models.CharField(choices=[('STUDENT_FEES', 'Student fees'), ('POCKET_MONEY', 'Pocket money'), ('PETTY_CASHBOOK', 'Petty cashbook'), ('CAPITATION', 'Capitation grant'), ('OPERATIONS', 'Operations'), ('CAPITAL', 'Capital'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('bank_reference', models.CharField(blank=True, max_length=120)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('RECONCILED', 'Reconciled')], default='UNMATCHED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_bank_statement_entry',
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitationGrantEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('RECEIPT', 'Grant receipt'), ('UTILISATION', 'Utilisation')], max_length=20)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period_label', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitation_entries', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitation_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_capitation_grant_entry',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=40, unique=True)),
                ('make_model', models.CharField(blank=True, max_length=120)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('VAN', 'Van'), ('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('OTHER', 'Other')], default='BUS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_vehicles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_fleet_vehicle',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=160)),
                ('employee_code', models.CharField(blank=True, max_length=40)),
                ('pay_period', models.CharField(blank=True, max_length=80)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_payroll_entry',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('REPAIR', 'Repair and maintenance'), ('INSURANCE', 'Insurance'), ('LICENCE', 'Licence / permits'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_expenses', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='billing.fleetvehicle')),
            ],
            options={
                'db_table': 'accounts_vehicle_expense',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
