# Generated by Django 5.0.14 on 2026-10-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_ops_capitation_payroll_transport_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitationgrantentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='capitationgrantentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicleexpense',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicleexpense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='vehicleexpense',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='BankStatementEntry',
        ),
        migrations.DeleteModel(
            name='CapitationGrantEntry',
        ),
        migrations.DeleteModel(
            name='FleetVehicle',
        ),
        migrations.DeleteModel(
            name='PayrollEntry',
        ),
        migrations.DeleteModel(
            name='VehicleExpense',
        ),
    ]
