# Generated by Django 5.0.14 on 2026-10-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_remove_ops_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountwithdraw',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('BARTER', 'Barter trade'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('BARTER', 'Barter trade'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesupplierpayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank transfer'), ('CHEQUE', 'Cheque'), ('BARTER', 'Barter trade'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
