# Generated by Django 5.0.14 on 2026-10-08 06:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_schoolaccount_vote_fund_disabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPocketMoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveBigIntegerField(db_index=True, help_text='admissions_student.id (no DB FK — shared with ADMINISTRATION)')),
                ('direction', models.CharField(choices=[('CREDIT', 'Top up'), ('DEBIT', 'Withdraw')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('MANUAL_MPESA', 'Manual M-Pesa'), ('STK_PUSH', 'STK Push (M-Pesa)'), ('CHEQUE', 'Cheque'), ('BANK', 'Bank transfer'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(max_length=120)),
                ('reference_code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pocket_money_entries', to='billing.schoolaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocket_money_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_student_pocket_money_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'student_id'], name='accounts_st_account_72d645_idx')],
            },
        ),
    ]
