# Generated by Django 5.0.14 on 2026-10-08 11:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0029_student_pocket_money_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="storestockmovement",
            name="unit_buying_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Buying price per unit at stock in.",
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01"))
                ],
            ),
        ),
    ]
